version: '3.9'

services:
  db:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
      - ./scripts/init-db-test.sql:/docker-entrypoint-initdb.d/init-db-test.sql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mindlink_service
    healthcheck:
      test: 'mysqladmin ping --silent'
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

  app:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - ./environments/.env.docker:/environments/.env
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  db-data: {}
